add "maptools:drowning"
minetest-mods/maptools pull request #18
Opened 2020-06-01 14:58 UTC by BuckarooBanzay

fixes #17

2020-06-01 17:46 UTC, Calinou requested changes
Should be good to merge after applying the suggestion :slightly_smiling_face:

2020-06-01 17:46 UTC, Calinou commented on NODES_ITEMS.md
> +| `maptools:drowning`     | :warning: Simulates drowning in water                                          |
```suggestion
| `maptools:drowning`     | :warning: Simulates drowning in water.                                         |
```

2020-06-02 07:13 UTC, Calinou approved these changes
Thanks!

2020-06-02 07:13 UTC, merged

2020-06-02 07:19 UTC, BuckarooBanzay commented
thanks for the quick response :+1: